########################################################
#                  InfoHeads v@version@                   #
# - Authors: Harry0198, Lorenzo0111                    #
# - License: FREE! (Well... Actually it's Apache-2.0)  #
#                                                      #
#                 Enjoy the Plugin!                    #
########################################################
#
# PlaceHolderAPI: You can use placeholders provided by PAPI.
#
# Change the default heads that you receive in the InfoHeads Wizard here.
# You can use custom heads from HeadDatabase, by using "id:<head id>"
#
# Documentation: https://docs.rocketplugins.space/infoheads
Heads:
  - 'MHF_Question'
  - 'MHF_Exclamation'
  - 'MHF_Chest'
  - 'MHF_Facebook'
  - 'MHF_ArrowUp'
  - 'MHF_ArrowDown'
  - 'MHF_ArrowLeft'
  - 'MHF_ArrowRight'

config-ver: 2
check-for-update: true