name: InfoHeads
main: com.haroldstudios.infoheads.InfoHeads
version: @version@
authors:
  - Harolds
  - Lorenzo0111
description: InfoHeads plugin!
api-version: 1.13
softdepend:
  - PlaceholderAPI
  - HeadDatabase
  - BlockParticles
  - Multiverse-Core

permissions:
  infoheads.use:
    default: true