name: InfoHeads
main: com.haroldstudios.infoheads.InfoHeads
version: ${project.version}
author: Harolds
description: InfoHeads plugin!
api-version: 1.13
softdepend:
  - PlaceholderAPI
  - HeadDatabase