name: InfoHeads
main: me.harry0198.infoheads.folia.EntryPoint
version: @version@
authors:
  - Harolds
  - Lorenzo0111
description: InfoHeads plugin!
api-version: 1.20
folia-supported: true
softdepend:
  - PlaceholderAPI
  - Multiverse-Core

commands:
  infoheads:
    description: InfoHead plugin commands.
    aliases:
      - if
      - infohead
    usage: /<command> [subcommand]
permissions:
  infoheads.use:
    default: true
  infoheads.admin:
    default: false