name: InfoHeads
main: com.haroldstudios.infoheads.InfoHeads
version: 2.3.1
author: Harolds
description: InfoHeads plugin!
api-version: 1.13
softdepend:
  - PlaceholderAPI
  - HeadDatabase
  - BlockParticles

permissions:
  infoheads.use:
    default: true