name: InfoHeads
main: com.haroldstudios.infoheads.InfoHeads
version: 2.2.2
author: Harolds
description: InfoHeads plugin!
api-version: 1.13
softdepend:
  - PlaceholderAPI
  - HeadDatabase
  - BlockParticles