name: InfoHeads
main: com.haroldstudios.infoheads.InfoHeads
version: v-2.2.0
author: Harolds
description: InfoHeads plugin!
api-version: 1.13
softdepend:
  - PlaceholderAPI
  - HeadDatabase
  - BlockParticles